name: Build and Release LuaSocket DLLs

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and run container
        run: |
          docker compose -f docker-compose.yml up --build

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: luasocket-release
          path: |
            output/luasocket.zip
            output/src_luasocket.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          name: luasocket-release

      - name: Set Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: |
            luasocket.zip
            src_luasocket.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
