name: Build LuaSocket for Lua 5.4.1 (Windows DLLs)

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container
        run: docker compose build

      - name: Run build
        run: docker compose up

      - name: Upload luasocket.zip
        uses: actions/upload-artifact@v4
        with:
          name: luasocket
          path: output/luasocket.zip

      - name: Upload src_luasocket.zip
        uses: actions/upload-artifact@v4
        with:
          name: src_luasocket
          path: output/src_luasocket.zip

      - name: Release DLLs
        uses: softprops/action-gh-release@v2
        with:
          files: |
            output/luasocket.zip
            output/src_luasocket.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
